### ISSUE TITLE
We support Dynamic Routes and getStaticProps Pages from next.js?

### ISSUE THREAD

**Issue by KULTI1995** [hozana/next-translate-routes#59] opened 2023-01-05 17:09 UTC
Do you guys support, generating the correct link ?

E.g. we have articles in different languages

https://nextjs.org/docs/advanced-features/i18n-routing#dynamic-routes-and-getstaticprops-pages

**Comment by ucarno** [comment] 2023-01-13 10:14
Really need this feature too

**Comment by draxx318** [comment] 2023-01-26 13:24
It looks like its impossible to combine this library with SSG sadly. I hope this feature will be added soon.

**Comment by stovein** [comment] 2023-02-08 20:02
Hi, @draxx318 is there any improvements on solution?

**Comment by cvolant** [comment] 2023-02-17 10:12
Sorry, I don't get it, could you explain your issue?
I also have some `getStaticPaths` and it works well...
You should not have anything to do here: `getStaticPaths` creates the dynamic file paths, which is then redirected and rewritten using next-translate-routes.

**Comment by wangwailok** [comment] 2023-02-28 11:41
> Sorry, I don't get it, could you explain your issue? I also have some `getStaticPaths` and it works well... You should not have anything to do here: `getStaticPaths` creates the dynamic file paths, which is then redirected and rewritten using next-translate-routes.

I am facing the same problem : getStaticProps does not work with translated routes
if you refresh the page, props was passed from getStaticProps.
but if you click the <Link> from translateRoute, the page wont grab props from getStaticProps

**Comment by wangwailok** [comment] 2023-02-28 11:43
> It seems like getStaticPaths does not get the translated routes from the _routes.json file. It looks like it's impossible to combine this library with SSG sadly. I hope this feature will be added soon.
> 
> Edit: I made it work, going to post the solution later.

Can't wait to see your solution!

**Comment by cvolant** [comment] 2023-03-01 12:53
:thinking: Strange... I don't have this issue anywhere. Could you provide a minimal reproduction?

**Comment by wangwailok** [comment] 2023-03-02 04:06
I just found out that if your file contains middleware.ts, getStaticProps will immediately fail.

**Comment by cvolant** [comment] 2023-03-02 15:56
> I just found out that if your file contains middleware.ts, getStaticProps will immediately fail.

Yes. See [here](https://github.com/hozana/next-translate-routes#middleware-with-watcher-next-1220)

So this issue is a duplicate of [this one](https://github.com/vercel/next.js/issues/39531), let's close it.

**Closed by cvolant** 2023-03-02 15:56 UTC
Labels: needs details/reproduction
